# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/php:8.3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo docker-php-ext-install opcache
            sudo docker-php-ext-install gmp
            composer install
      - run:
          name: Run tests
          command: |
            composer run-script phpunit

  build:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build --tag $DOCKERHUB_USERNAME/freshrss:$TAG -f Docker/Dockerfile-Newest .
      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/freshrss:$TAG

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
