# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version:
  2.1

  # sudo docker-php-ext-install opcache
  # sudo docker-php-ext-install gmp

jobs:
  test:
    docker:
      - image: cimg/php:8.3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            composer install --ignore-platform-req=ext-gmp --ignore-platform-req=ext-zend-opcache
            composer require --ignore-platform-req=ext-gmp --ignore-platform-req=ext-zend-opcache --dev previousnext/phpunit-finder
      - run:
          name: Run tests
          command: |
            TESTS_TO_RUN=$(/data/vendor/bin/phpunit-finder -- functional)
            echo "$TESTS_TO_RUN" | circleci tests run --command="xargs -I{} -d\" \" /data/vendor/bin/phpunit {} --log-junit /data/artifacts/phpunit/phpunit-functional-$(basename {}).xml" --verbose --split-by=timings

      - store_test_results:
          path: artifacts/phpunit

  build:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build --tag $DOCKERHUB_USERNAME/freshrss:$TAG -f Docker/Dockerfile-Newest .
      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/freshrss:$TAG

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
